version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: react-toastify
    versions:
    - 7.0.2
- package-ecosystem: npm
  directory: "/backend"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
